#include "BCU_Data/BCU_data.hpp"
float BCU_data::charge_voltage;
uint8_t BCU_data::duty_u;
uint8_t BCU_data::duty_v;
uint8_t BCU_data::duty_w;
float BCU_data::angular_velocity;
uint16_t BCU_data::ref_q;
uint16_t BCU_data::ref_d;
float BCU_data::ref_speed;
float BCU_data::ref_switch_freq;
float BCU_data::ref_dead_time;
float BCU_data::fixed_dc_link_vtg;